---
title: "E80 Project Field Deployments"
---

You test your assembled robot by performing field deployments to gather live data from your sensors.  The data you gather during these deployments is essential for your [final report and presentation](/project/report).  There are two deployments, one at pHake Lake during your normal lab section during the week of {{<var dates.phake1>}}, and the second at Dana Point on Saturday {{<var dates.dana>}}.  This document describes the deployments, the build time between deployments, and additional details about best practices during a deployment.


## pHake Lake

You are expected to test your AUV at the pHake Lake at the Bernard Field Station during your regular section time in the first deployment week (the week of {{<var dates.phake1>}}). You must be at the [side gate](https://drive.google.com/file/d/1wdGyp2_50KINmBhqCJby9zoKUE3Mr1cf/view?usp=sharing) of Bernard Field Station by 1:15 pm on the day of your deployment. An instructor will meet the group at the gate at the start of your section.  The main E80 Lab (Parsons B171) will be open from 12:30 pm - 1:00 pm this week so that you may retrieve your equipment.

The goals of this test are: 

1. Make sure your sensors and integrated robot work in the field
2. Evaluate the quality of your data so you can improve it before your second deployment. There is about 1.5 weeks between this deployment and Dana Point, so you have some time to make changes.
3. Acquire data that can be used in your final report and presentation in case something goes wrong in your second deployment. 

Safety information:

- Be sure to walk to the BFS gate in pairs and **only cross at crosswalks**.
- Sunscreen and water will be available during this deployment, but be sure you've eaten before you arrive.
- Faculty will announce a cancellation of the launch in the case of severe rain. 

Resources information:

- The [mobile lab facility](/reference/equipment) will be available at BFS.
- The teaching team will be out at BFS during deployments. 

## Rebuild Week 

The week between your pHake Lake deployment and Dana Point is your final chance to test and verify your deployment checklist and fix any flaws that were discovered at pHake Lake. You will have your regular section time to rebuild, retest, and modify your system to get more meaningful data by adjusting such things as amplifier gains and offsets, sampling rate, sensor location on the AUV, and deployment times of your sensor. You will not have access to pHake Lake, but you will have access to the water tank during the week.

## Dana Point

The final field deployment is on Saturday, {{<var dates.dana>}}. Here are important details:

- We will take buses from Foothill Blvd just north of Parsons to Dana Point, leaving at 6:30 am sharp. <br> **If you miss the bus, you will have to find your own way to Dana Point.**  
- Make sure your team is outside Parsons with your robot at 6:00 AM. Also make sure your team has gathered any extra supplies that you plan to bring before 6:00AM. 
- Attendance will be taken to ensure that the bus doesn't leave anyone behind at the end of the day, so make sure you are counted in the morning. Also make sure that you tell us if you are leaving separately from the bus.

Safety information:

- Sunscreen and water will be provided
- Snacks and lunch (pizza, granola bars, chips) will be provided. 
- Faculty will announce a cancellation of the launch in the case of severe rain. The launch may be rescheduled for Sunday in that case.

Food information and Dietary Restrictions:

- Breakfast pastries will be provided before you board the bus.  If your dietary restrictions prevent eating breakfast pastries, please arrange for your own breakfast.
- Contact {{<var people.dana_point_food>}} as soon as possible if your dietary restrictions prevent eating pizza for lunch. We will arrange for an alternative. 

Resources information:

- The [mobile lab facility](/reference/equipment) will be available. 
- In addition, we will provide freshwater buckets and rice for recovering flooded robots.

You are not allowed to do any deployments after launch day, so use this deployment well!


## Best Practices

Deploying a robot is complicated business, and it's easy to make a mistake.  Following the best practices described in this section reduce the chance that you'll make a mistake and increase the chances that you'll get good data.

**Safety Lines** If your robot is diving, tie a string to it before you deploy it.  Keep the string slack during deployment if things are going well, or use it to pull the robot to safety if things are going poorly.

**Boat Escorts** If your robot is unreachable from shore, which is common when surface navigating, then keeping a boat nearby is a good way to ensure that your robot can be recovered in case it does anything unsafe or risks damage to itself.

**Calibrations** Some sensors need to be recalibrated on site.  Notably, magnetometer coefficients vary with your declination from the pole, and atmospheric pressure varies with your distance from sea level.  You may also need to tune the range on light or temperature sensors to account for local brightness or water temperature.  Be ready to do some basic calibrations on site, and be sure to do some test runs to make sure that your sensor outputs are in range before committing to a major deployment.

**Ground Truth**: You should take a ground truth measurement before each deployment so that you know the basic conditions your robot will deploy into.  For instance, you could measure water temperature with a digital thermometer before putting your temperature-measuring robot in the water.  This is essential for detecting bugs in your sensors or calibration: if you only have your robot data to work with, and your robot data is flawed, it's difficult to back out what went wrong (or even detect that something went wrong).

**Save your Data**: Field data is precious, even if it looks bad.  Make sure to save it!  Save all of your data, and don't leave it on the SD card to get accidentally deleted.  It is helpful to have a folder where you can store all your data for each deployment, and to keep a spreadsheet in that folder so you can make notes about each file (when it was run, deployment location, notes on anything weird that happened, etc.).

**Preview your Data**: After you deploy your robot, you should check your data to see if it matches your ground truth and your expected behavior.  To do this, you should have some Matlab or other visualization software ready before deployment.  This step is important because it tells you if your deployment worked properly while you still have time to redeploy.

**Experimental Plan** Most of the advice above is concerned with an individual deployment, but you should also be thinking holistically about your experimental goals while deploying.  How many deployments do you need, from what locations, and at what times of day?  The experimental plan is the place to write down these details. The plan should  also list the expected range of signals you expect to observe (based on theory or preliminary measurements) during the deployments. Finally, in the case of surface navigation, the plan should show the intended robot trajectory for each deployment and list how the robot will be recovered (kayak, it comes back and we grab it, pool hook, etc.).

**Checklist**: Most of the advice in this section is gives you more work to do before you launch.  It's very easy to forget a step and launch in a way that corrupts your data.  The surest proof against such a mistake is writing a deployment checklist that spells out all the steps you should do before a launch.  Use the checklist during a launch by having one team member read steps off of it while another works on the robot and verifies that steps are complete.  Here is an [example deployment checklist](https://drive.google.com/open?id=1MWqGn4acs9HfsRtGSR8tZrp-E_IN6IH4).

There are some additional practices that will help when you prepare specifically for deploying at Dana Point:

**Buoyancy**: Seawater and lake water have very different densities. A neutrally buoyant AUV in pHake Lake will bob like a cork in the ocean.  Be ready to trim your ballast appropriately.

**Electrical Coupling**: Salt water and fresh water have very different conductivities, and that can affect the performance of your sensors in surprising ways.  One thing we've noticed is that motor noise couples into sensors much more aggressively in salt water than in fresh water.  Test this behavior in the salt water bath at Mudd, and consider stopping your motors during your deployment to take clean data.  (This is easier in surface deployments than in dives because you need to maintain your depth during a dive.)
