---
title: "Lab Overview"
---

Put these crucial lab and project dates on your calendar!

- Friday {{<var dates.kickoff>}}, 1:15PM-3:15PM: Kickoff lecture in {{<var rooms.kickoff>}}
- Friday {{<var dates.project_kickoff>}}, 1:15PM-3:15PM:  Project kickoff lecture in {{<var rooms.project_kickoff>}}
- **Saturday** {{<var dates.dana>}}, 6:30AM-5:30PM:   Robot deployment *on Saturday*  at Dana Point. <br> **ALL STUDENTS ARE EXPECTED TO ATTEND THE SATURDAY LAUNCH**
- Wednesday {{<var dates.present>}}, time TBD:   Project presentations for all groups during presentation days.

## Labs

Lab manuals are linked here. Deliverables for each lab are detailed on their individual pages.

Note that in weeks 6 and 7, the order of Lectures/quiz/Lab are not the same for everyone. Odd numbered teams (11, 23, etc.) do different work than Even numbered teams (12, 24, etc.). **Please make sure prelab is done for the correct lab.**

A submission sheet is due at the end of each 4-hour lab period. The submission sheet must be uploaded before the end of your lab session at 5:15 pm. Note that only **ONE** member of each team should access and submit the submission sheet. It is the responsibility of that team member to add the rest of the team’s names to the submission sheet. 

| Week | Lab                                                | Notes about Friday     | 
|------|----------------------------------------------------|------------------------|
| 1    | [Lab 0: Tutorial and Skill Review](/labs/lab0)     | Kickoff lecture        | 
| 2    | [Lab 1: Go Autonomous](/labs/lab1)                 |                        |
| 3    | [Lab 2: Basic Electrical Measurements](/labs/lab2) |                        |
| 4    | [Lab 3: Op Amps and Marine Sensors](/labs/lab3)    |                        |
| 5    | [Lab 4: Temperature Sensors](/labs/lab4)           |                        |
| 6    | Odd Numbered Teams: [Lab 5: Underwater Acoustics](/labs/lab5) <br> Even Numbered Teams: [Lab 6: Fluid Mechanics](/labs/lab6) |                         |
| 7    | Odd Numbered Teams: [Lab 6: Fluid Mechanics](/labs/lab6) <br> Even Numbered Teams: [Lab 5: Underwater Acoustics](/labs/lab5) | Project kickoff lecture | 
| 8    | [Project Proposal Week](/project/proposal)         | Proposal and tech memo |
| 9    | Spring Break                                       |                        |

## General rules
- No eating or drinking in lab. If necessary you may leave lab, wash your hands, eat and/or drink something outside the lab, wash your hands, return to lab.
- Know the location of fire extinguisher, eye wash, safety shower and quickest escape route.
- Notify instructor immediately after _any_ injury, fire, spills or breakage.
- Clean lab bench and turn off equipment before leaving. Leave the bench power on.
- Electricity and water DO NOT MIX –a lot of water is involved in E80 – be mindful at all times.

## Proper attire
- Closed-toe shoes
- Short sleeves preferred, rolled-up long sleeves acceptable
- Long pants
- No dangling jewelry – no rings, bracelets, necklaces or earrings
- Loose clothing must be secured away from work (including hoody draw strings)
- Long hair pulled back and secured
- For field experiences:
  - Location-appropriate footwear and clothing
  - Appropriate PPE (including floatation devices for boats)
  - Sunscreen
  - Hydration

## Chemical safety

In this class, this primarily applies to epoxies and CyanoAcrylate (aka CA, aka superglue)

- Safety goggles
- Gloves
- If procedure emits fumes, then must be done in a fume hood or out of doors away from buildings

## Soldering
- Iron must be turned off when not in your hand.
- Use recently soaked sponge. Use spray bottle to moisten. Never use sink or water fountain.
- Use fume extractor: fume from rosin in solder is a respiratory irritant.
- Wash hands after handling solder – solder is 40% lead.  Skin contact is harmless, but ingestion can occur with unwashed hands when eating, drinking, or smoking.

## Hardware checkout
You will work with some expensive hardware in this class. Expensive hardware like motherboards and batteries must be explicitly checked out from a professor or proctor so that we can track where it is. If any hardware that you checked out breaks,  you will need to request a replacement from a professor. You make this request by filling out an [error report](https://drive.google.com/open?id=1FnHDzDSCuc3pAsEXzUg6BnTacfLF-ODs) (paper copies will be in lab). This report needs to be well thought out; professors will reject reports that don't represent sufficient testing or thought. You will keep this hardware with you throughout the semester in your storage box. 

## Warning Callouts
Labs will include warning callout boxes, an example of which is below, to indicate safety hazards.  All group members must understand the warning and associated safety precaution before lab.  Failing to carefully read warnings can damage equipment or harm lab users.  You should always feel empowered to stop work and grab an instructor if you find a warning that makes you unsure.

:::{.callout-warning}

This text would describe a way that you can injure yourself or damage equipment.
:::
