---
title: "History"
---

## 2023

An [ASV with a side-scan sonar](img/IMG_0073.JPG) that successfully [mapped the depths of Dana Point](img/side_scan_data.png).

An [AUV that measured light intensity](https://drive.google.com/file/d/1EBH-23sqoNi2aSR8oisyuDFHgmclQUPq/view?usp=sharing) at different colors vs. depth with an unusually good calibration scheme involving [a Go-Pro that descended with the AUV](https://drive.google.com/file/d/1mi6jaRq8IQ_dZmOhy1kvfyUiDuMfUEqh/view?usp=sharing).

## 2019

Students [built a microscope](img/microscope_camera.png) that operated during an ASV deployment.  The video from the microscope, and consultation with a microbiologist, allowed the team to identify a variety of [marine microbes](img/microscope_microbes.png).

## 2018

A cleverly designed [bottom crawler](https://drive.google.com/file/d/1s1zsGPTx-QZpVYCwWR4Md5jM4KVQRcAZ/view) used powerful motors and a tethered surface skiff to map depth along accurate trajectories.  

An ASV used a [particle filter based navigation](https://drive.google.com/file/d/1hbRGmwnh3ZMJ5kYYFFD54oPrNAFauuVd/view) and error correction system to achieve unusually good trajectory accuracy.

## 2017

An [acoustic beacon tracker](https://drive.google.com/file/d/1nXRh81PjcI-u6L069lIfVtWcA4mYu-3c/view) deployed in the Mudd test tank.  The oscillations in it's trajectory are characteristic of angle control based on stereo sensors, and the team had a MATLAB model which showed the same behavior.

A [wind-measuring ASV](https://drive.google.com/file/d/1RJtr_GxRZIaCJ95jLnJmj6HU9P30WT7T/view) did an exceptionally good job of sensor calibration, including using the wind tunnel to calibrate sensors.

## Older Versions of E80

E80 has a long history, and any success of the current version is due to building on its predecessors: 

* 2009-2016: E80 was based on building and launching rockets under Erik Spjut and Mary Cardenas.  See [here](https://pages.hmc.edu/spjut/RocketE80/index.html)
* 2000-2009: E80 was based on field experiments where students struck bridges with impact hammers under Ziyad Duron.
* Pre-2000: E54 saw students complete a variety of experiments under a long list of professors, including an infamous bucket-based clock.  See an old lab manual [here](./assets/E54_Course%20Notes_1992.pdf)
