---
title: "Lab Equipment"
---

| Name                     | Part Number & Datasheet | 
---------------------------|-------------------------|
| Oscilloscope             | [Agilent 2024A](http://literature.cdn.keysight.com/litweb/pdf/5990-6618EN.pdf) | 
| (Gray) Oscilloscope Probe | [Keysight N2842A](https://assets.testequity.com/te1/Documents/pdf/keysight/N28xxA-ds.pdf) | 
| Function Generator       | See WaveGen section of oscilloscope manual. | 
| Old Function Generator   | [HP/Agilent 33120A](https://www.keysight.com/us/en/assets/9018-04436/user-manuals/9018-04436.pdf) | 
| Power Supply             | [Keysight E2630A](https://www.keysight.com/us/en/assets/7018-06784/data-sheets/5968-9727.pdf) | 
| Multimeter               | [Greenlee DM-210A Digital Multimeter](https://cdn.greenlee.com/resources/media?key=7fe82ac7-208f-4c14-910c-a522a2949b3c&languageCode=en&type=document) | 


## Mobile Lab Facility

During field deployments the E80 staff sets up a mobile lab facility to enable students to prototype and debug. It has the following equipment available:

- A set of work tables set up beneath shaded tents.  
- A solar generator/battery sufficient to power the lab and charge a limited number of laptops. 
- Power supplies 
- Oscilloscopes 
- Soldering irons 
- Some electronics supplies ~ op-amps and resistors. 
- Multimeters 
- Common hand tools (wire strippers, diagonal cutters, screwdrivers, etc.)
- Heat shrink
- Glue
- Hot air guns