---
title: "E80 Project Presentation and Report"
---

Final Presentation Rubric [html](presentation_rubric.qmd) [docx](presentation_rubric.docx)

Final Report Rubric [html](report_rubric.qmd) [docx](report_rubric.docx)

Peer Review Feedback Instructions [html](peer-review-instructions.qmd)

Peer Review Worksheet [html](peer-review-worksheet.qmd) [docx](peer-review-worksheet.docx)

Final Presentation Schedule [gdoc]({{<var urls.final_presentation_schedule>}})

## Instructions

The final week of the project is dedicated to analyzing your data, figuring out how to report it, and doing end-of-class surveys.  After that, you prepare and deliver a final report and presentation to describe your efforts.  This document describes the analysis week, the final report, and the final presentation.

## Analysis Week

Though you are still free to work on your report and analysis in office hours and other E80 sections this week, **you are required to attend your lab section**.  This is because we will do a few required activities, listed below, in lab.  Some optional activities are available too.

**Required: Fill out the end-of-semester evaluation** -- We are going to give you time in lab to fill out your end-of-semester course evaluations and the E80 post-survey.  Note that participating in these evaluations is worth points on your final grade. Be sure to fill out an evaluation for your section professor.  Odd numbered teams should also fill out a second evaluation for {{<var people.dev1>}}, and even numbered teams should also fill out a second evaluation for {{<var people.dev2>}}.

**Required: Have a writing conference with an instructor** -- You will also have a scheduled conference with an instructor where we will sit with your team to discuss our feedback on your Lab 6 tech memo.
The goal of this meeting will be to share high-level feedback on what you did well and to suggest areas for improvement on your final report.
A schedule of conference times and locations will be circulated via Discord.

**Optional: Work with your team on writing and producing slides** -- All of your team members are guaranteed to be available during your lab section, so this can be high value writing and discussion time. Teaching staff will also be available to answer questions about writing and data presentation.

**Optional: Conduct forensic experiments if needed** -- Experiments during analysis week are strictly limited, except for a very limited subset of measurements that we call "forensic experiments".  These experiments are allowed to help you figure out how a subsystem failed, or what you are seeing in your data.  They are not intended to be additional deployments.  Ask an instructor if you're unsure whether your experiment should be allowed.

Examples of good forensic experiments:

- A team needed to see how their measurements from an LED varied with angle to decipher their data, so they took their still functional sensor outside and waved it around to take that measurement.
- A team had inconsistent logging, so they turned their robot on and off with the box open and closed to prove that squeezing one particular wire caused the problem.

Examples of experiments that we don't want to see, which are outside the bounds of forensic experiments:

- Deploying your robot at pHake Lake.
- Deploying your robot in the test tank as a substitute deployment.  Some very limited experiments may be OK (eg: to prove that you leak when you're 1 m underwater), but an autonomous run to show your sensors working is not.
- Building or measuring new sensors; if it didn't work, at least partially, during a deployment, then we're not interested in seeing it in a final report.

## Recommended Outline

Both your presentation and your final report will be telling a similar story: why did you do a robot deployment, what are the technical details of how your robot worked, and what can the audience take away from that.  Therefore, we expect that most reports (and presentations) will be organized as below.

All reports and presentations must contain the following:

* Description of safety precautions that you took during your robot deployment to ensure that you gathered data in a way that protected the environment and other people.

Successful reports and presentations usually include discussions of: 

* Science and/or engineering goals
* Sensors and mechanical modifications to achieve those goals
* Design process and calculations
* Pre-deployment modeling and expected measurements
* Data processing
* Comparisons between modeling and measured data
* Interpretation of these results
* Recommendations for future work

This content is typically organized as follows (note that the report will also need an abstract even though it is not listed here):

1. Introduction - Describe your scientific or engineering goals.
2. Sensor Design - for each sensor
    a. Theory of Input Quantity - What are the expected sensor input sizes (e.g.: temperature swings)  from theory or historical data?
    b. Sensor Selection - What sensors did you select? Why? Do they match expected behavior.
    c. Circuit Design - Show full schematics, calculations used to select components, and calculations showing that signals will be in range for the Teensy.
    d. Software Considerations - Is the 10 Hz `default_robot.ino` sampling rate fast enough? Did you write any additional code for the sensor?
    e. Sensor Validation/Calibration - Show the sensor working in controlled conditions.
3. Robot Design - Show mechanical calculations, sensor mounting designs, unusual details of waterproofing, and schematics for other circuits that haven't been discussed yet (eg: regulators).
4. Deployment Details - What steps were taken to prepare your robot for deployment? Where were the deployments (and what were the trajectories)? How did you account for safety in your deployments?
5. Results - Include comparisons to theoretical models and ground truth measurements.
6. Conclusion - Provide a recap, recommendations for future work, interpretation of results, and a main takeaway for the audience.

It is possible to deviate from this outline if doing so would tell your robot's story better, but this works well for almost all E80 deployments. Feel free to discuss such changes to the outline with instructors.

## Final Presentation

On presentation day, {{<var dates.present>}}, you will give a fifteen-minute, in-person presentation followed by ten minutes of questions and answers. This presentation should be aimed at a technically competent audience with diverse training backgrounds that is unfamiliar with the details of your project. (e.g.: The audience is a group of professional engineers from different disciplines.)  Every member of the team should participate in the presentation.  Presentations will be graded using this [rubric](presentation_rubric.qmd).

You should imagine the presentation is being given to employers or peers at a conference, which means that you should hold yourself to high standards of professionalism: 

- practice until the presentation is smooth and well-polished, 
- think carefully about the story your visual aids are telling, 
- ensure that the visual aids are readable and high quality, and 
- dress in [traditional business](http://www.casualpower.com/business_casual_tips/biz_attire.html) or [business casual](http://www.wisegeek.org/what-is-meant-by-business-casual-dress.htm) clothing. 

The questions during the Q&A portion of your presentation will come from both the general technical audience and your instructors. They will range from straightforward to very detailed. Be sure to prepare by practicing fielding pointed questions and by cultivating a comprehensive understanding of your work. Preparing supplementary slides which you can deploy for common questions can help you during the Q&A.

The presentation schedule is available [here]({{<var urls.final_presentation_schedule>}}).
Please be at least ten minutes early to your presentation.  



## Final Report

Each team is responsible for submitting a report on their deployments in [IEEE format](https://www.ieee.org/conferences/publishing/templates.html). The report has a maximum length of ten pages including figures, references and appendices. Your purpose is to convey your experiments, your apparatus and your results such that a reader could replicate your experiment and compare their results to yours. You should assume your audience is made of technical professionals of diverse backgrounds (i.e.: not all instructors of the course) who are unfamiliar with your specific project. Note that this is a different audience than the  presentation. [This rubric](report_rubric.qmd) will be used to grade the reports.   

Here are a few tips for good report writing:

* The main body is often most digestible if it is written in several sections. Which sections are included and the ordering of your will depend on the specifics of the experiment, but some common, important topics are provided in the modified rubric. 
* If it is impossible to address every point in the modified rubric while staying inside the page limit then (1) make your writing more compact by using mathematical notation, tables or figures and (2) prioritize what is most important for your report. 
* Be sure to follow the practices of scientific writing: use quantifiable descriptions instead of vague adjectives ("a 25% change" instead of a "a big change"), make sure all plots have labeled axes with units, make sure text in figures and tables is large enough to read, don't use the first person (including cheats like "the team did X") and minimize passive voice by making the experiment or artifact the subject of your sentences.
* Make sure to do some pre-writing to organize your text. Decide what topics you want in the report and where you want to put them before you start writing. Don't talk about topics in the wrong sections or repeat yourself unnecessarily.
* Don't forget that your writing style has a huge impact on how your work is received. Make a careful editing pass to be sure that each sentence says what you mean it to say. Then make a second editing pass for spelling, punctuation, common grammatical errors (especially tense mismatch, which is endemic), and gracefulness of language.

Here are [some examples](https://drive.google.com/file/d/1S9CDXcDnjuwNG8Eaq6cG5EOcC_Bojqcw/view?usp=sharing) of student reports.

A rough draft of your final report is due at 5:00 PM on the last day of classes.

The final draft is due at at 11:59 PM the day before your final presentation.