---
title: "E80 Project Report Peer Review"
format:
  html: default
---

Peer Review Worksheet [html](./peer-review-worksheet.qmd) [docx](./peer-review-worksheet.docx)

## The Purpose of Peer Review

The purpose of peer review is to help you to get feedback on your writing.
This page describes the process we will use in E80 for you to give and receive feedback on your final reports.
First we start with instructions on how to give and receive good feedback.
Then, you will complete the form included below under [Project Peer Review](#project-peer-review).

## On Giving Feedback

1. **Focus on the big stuff.**: Is the main claim clear? Is their sufficient evidence to support it? Are the ideas explained well? Are paragraphs focused on just a single idea? Where can the data be presented more clearly?
2. **Trust your gut.** If something feels wrong to you as a reader, it probably can be improved. Do your best to explain why you feel something could be improved and give a suggestion on how to improve it.
3. **Praise what works well.** When something is done well, say so!
4. **Give kind and honest feedback for improvement.** Writing is a never-ending process of revision. There is always something to be improved. Your peer's work almost certainly could benefit from some revision so be polite and direct about how you think the work could be improved.
5. **Give thoughtful comments.** Try to be as specific in your comments as you can. If possible, explain what you sense is wrong and suggest how it could be changed. If possible, ask questions for the author to consider before they would revise.
6. **Step back.** It's easy to get wrapped up in the minutia while we read. Make sure to step back at the end to see how the report fits together as a whole.

## On Getting Feedback


1.	**Appreciate the gift you’ve been given.**
Someone took the time to read your writing.
This is truly a gift!
You are being called to improve your work because it has value and because your project is worth making clearer and better.
By listening to your peers, you save yourself a great deal of stress and work: they are telling you what is and isn’t coming across clearly so you can revise effectively.
2.	**Remember: clarity is in the eye of the reader, not the writer.**
In large part, your audience is the best judge of your work.
You’re likely too close to your ideas and intentions to see if they are best captured in your writing.
3.	**You needn’t “defend” your work.**
We can generally assume that you, the author, didn’t intend for things to be unclear.
And we can assume that your peer reviewer is trying to identify lack of clarity, not request an explanation of your specific thought processes as you wrote.
Therefore, it isn’t really that helpful to explain away to your peer why you wrote what you wrote unless they ask for such an explanation.
Instead, you want to focus on how you can clarify things—e.g., “Would it be clearer if I did x instead of y?”
4.	**Consider each comment, but you needn’t revise on behalf of each.**
If your peers say something could use improvement, please take their comments seriously.
Upon reflection, though, you might think it best not to make changes.
Perhaps you have good reasons for what you have written; perhaps other revisions will clear up the issue in question.
5.	**Ask for clarification on comments you receive.**  
If possible, chat with the people who gave you feedback to learn more about their comments and how you might improve your work.
6.	**Acknowledge people who give you feedback.**
It’s good practice to keep track of everyone who helped you in your project and to construct an acknowledgments page as part of your manuscript.  
7.	**Try to revise while comments are fresh; don’t forget to look for that small stuff once everything else is in order.**
Carve out time to make some notes on how you will revise.  When revision is done, proofread your work. And again.       



## Project Peer Review

First, turn on “track changes” or “suggesting” mode, since you are providing digital feedback (this is mostly to prevent you from accidentally changing the document in an untraceable way).
Carefully read through the entire work, inserting comments/questions into the margin using the “Insert Comment” feature on MS Word or Google docs.
Again, use the Insert Comments feature; don’t type onto the document itself.
Focus these comments on big things, such as thesis, topic sentences, evidence, etc.  

Second, complete the following questions for the paper you read.
You can also download this as a separate form here.
You'll need to turn this in on Canvas.

1. Generally speaking, what does this report do well?

2. Does this report incorporate...

   -  A clearly explained background

   - A clear conclusion and data to support it 

3. In your own words and without looking back at the report, write the main conclusion of the final project. Now, looking back at the report, does the actual thesis match what you wrote? Explain.

4. Does this report include effective topic sentences for the body paragraphs?

5. Does the report include sufficient data and figures to support the claims? How should the data presented or figures be modified to more clearly make the point?

6. What formatting mistakes exist in the report?

7. What aspect of the paper should the author focus most on in their revision?

8. What other comments would you like to add?

## Acknowledgements

This peer review worksheet is adapted with permission from a worksheet from Prof. Kyle Thompson at HMC.
His worksheet was in turn the result of collaborations with colleagues at HMC as well as making use of excellent guidelines and resources from the HMC Writing Center.