---
title: "E80 Project Report Peer Review Worksheet"
format:
  html: default
  docx: default
---

## Information

Your name: 

The name of the author you are reviewing:

## Peer Review Instructions

First, turn on “track changes” or “suggesting” mode, since you are providing digital feedback (this is mostly to prevent you from accidentally changing the document in an untraceable way).
Carefully read through the entire work, inserting comments/questions into the margin using the “Insert Comment” feature on MS Word or Google docs.
Again, use the Insert Comments feature; don’t type onto the document itself.
Focus these comments on big things, such as thesis, topic sentences, evidence, etc.  

Second, complete the following questions for the paper you read.
You may include your responses inline on the form below.

After you complete this form, submit both this form and a copy of the annotated report you reviewed to Canvas **and** send them to the person who's work you peer reviewed.

**1. Generally speaking, what does this report do well?**

**2. Does this report incorporate...**

**A clearly explained background**

**A clear conclusion and data to support it**

**3. In your own words and without looking back at the report, write the main conclusion of the final project. Now, looking back at the report, does the actual thesis match what you wrote? Explain.**

**4. Does this report include effective topic sentences for the body paragraphs?**

**5. Does the report include sufficient data and figures to support the claims? How should the data presented or figures be modified to more clearly make the point?**

**6. What formatting mistakes exist in the report?**

**7. What aspect of the paper should the author focus most on in their revision?**

**8. What other comments would you like to add?**

## Acknowledgements

This peer review worksheet is adapted with permission from a worksheet from Prof. Kyle Thompson at HMC.
His worksheet was in turn the result of collaborations with colleagues at HMC as well as making use of excellent guidelines and resources from the HMC Writing Center.