---
title: "Grading Rubric for E80 Final Presentation"
toc: false
format:
  html: default
  docx: default
---

## Technical content: (40%) 

4 – Exceptional: Relevant disciplinary facts are invoked, interpreted, and applied correctly. Analysis is carried out in-depth and thoroughly and supporting materials are sufficient and used wisely.

3 – Good: Appropriate disciplinary facts are invoked. Many good points are made but some analysis could provide more details or there is some uneven balance on the material.

2 – Marginal: Do not invoke all appropriate disciplinary facts. Many explanations are superficial or not thorough. Supporting materials are not clearly connected.

1 – Inadequate: Provide no evidence of awareness of relevant disciplinary facts.


## Organization and coherence: (20%) 

4 – Exceptional: Presentation is clearly stated and well developed. Pieces are well organized and flow logically. Introduction and conclusion are clear. Good transitions between pieces. 

3 – Good: Most information presented in a logical sequence, generally well organized but some parts may be underdeveloped or better transitions from idea to idea are needed.

 2 – Marginal: Concept and ideas are loosely connected. Part to part lacks a clear transition, and flow and organization are choppy.

1 – Inadequate: Presentation is choppy and disjointed. It does not flow in a logical order.


## Speaking skills and delivery (by team member) (20%) 

4 – Exceptional: Presenters show clear articulation with proper rate, good posture and gestures. Have constant eye contact with audience and enthusiasm and confidence.

3 – Good: Presenters show clear articulation but are not always polished. Postures and confidence are not always present. 

2 – Marginal: Articulation not clear all the time. Show little eye contact, inappropriate rate or lack of enthusiasm. May have noticeable vocalized pauses (uh, um etc) or read off a visible note card.

1 – Inadequate: Presenters are inaudible or too loud. No eye contact. Pace is too fast or slow. Seem uninterested or no enthusiasm on the subject. 

Team Member 1:

Team Member 2:

Team Member 3:

Team Member 4:

Team Member 5:

## Audience Engagement and Response (15%) 

4 – Exceptional: Clearly answer Q-A session questions. 

3 – Good: Most questions are answered well in Q-A session. Some questions may not be addressed completely.

2 – Marginal: Main questions in Q-A session are not clearly answered.

1 – Inadequate: Have great trouble in answering audience’s questions in Q-A session.

## Includes Required Sections (5%)

1 - Includes discussion of deployment safety considerations

0 - Does not include discussion of deployment safety considerations

## Additional Comments:

<textarea id="comments" name="comments" rows="10" cols="50">

</textarea>
