---
title: "Grading Rubric for E80 Final Report"
toc: true
number-sections: true
format:
  html: default
  docx: default
---


## Abstract 
The abstract articulates what was done, including a quick description of the experimental method. The abstract mentions quantitative conclusions.
Introduction/background 
The introduction motivates the work and explains experimental and modeling methods well enough to orient the reader to the paper.  The introduction does not explain technical details in more depth than necessary to orient the reader: those details belong in the main body.

* 5 – Motivates work, explains experimental and modeling methods well enough to orient the reader to the paper.
* 4 – Motivates work too much or too little, explains experimental and modeling methods weakly such that expectations of future sections are unclear.
* 3 –One of motivation or description of work/methods missing or very weak, the other serviceable.
* 2 – One of motivation or description of work/methods missing or very weak, the other poor.
* 1 – Missing both

## Main body 
The main body of the document provides the information necessary to understand and replicate the experiment.  The main body should be logically organized and should discuss every topic from the following list that is relevant to the robot’s mission.

### Scientific and/or Engineering Goals
An explanation of the specific phenomena the robot was designed to measure, why these measurements are important, and what can be learned from these measurements. A similar explanation should accompany each goal.

* 5 – As above. Theory of each goal articulated quantitatively with analysis of
confounding factors. Similar depth for each goal.
* 4 – Basic theory present for all goals but either not articulated quantitatively or missing confounding factors.
* 3 – Missing information on one goal. Partial information on multiple goals. Basic theory present but lacks quantitative rigor and analysis of confounding factors
* 2 – Basic theory not well articulated or incorrect for multiple goals.
* 1 – Hard to interpret. Goals missing.

### Sensor Selection 
A discussion of what sensors were chosen and how they relate to the scientific or engineering goals. The discussion should address the sensor input/excitation range and how these compare with the expected excitation during deployment. The discussion should also address the output range and or form (voltage, AC voltage or pulse train, pulse width modulated, pulse height modulated, etc.), and impedance. A similar analysis should accompany each sensor.

* 5 – As above. Expected input limits articulated quantitatively and backed with
analysis/simulation. Comparison of input limit to datasheet spec. Discussion of output range and time constant for each sensor.
* 4 – Missing input limits, output scale or time constant for a small fraction of sensors.
* 3 – Missing one of input limits, output scale, or time constant from most sensors or 2 of 3 for a small number of them.
* 2 – Missing two of input limits, output scale or time constant from most sensors.
* 1 – Analysis fundamentally wrong or missing.

### Circuit and Robot Design 
An explanation of the circuits that were designed. This should include discussion of the component values which were selected or calculated e.g.: to get the expected variations in output into the 0-to-3.3V input range of the Teensy. This should explain if the sample rate of 10 Hz was sufficient. This should also explain modifications to the robot which were made to ensure the sensor functioned properly (these may be in a separate mechanical design section).  A similar explanation should accompany each sensor.

* 5 – As above. Circuit topology, gain and signal conditioning discussed for each sensor. Power supplies and their uses enumerated. Mechanical modifications considered and well described.
* 4 – Purpose of some circuits is unclear. Omit description of some signal conditioning circuitry or decisions for calculating gain. Power supplies introduced without their uses. Missing schematics. Mechanical mounting omitted for some sensors or not in sufficient depth.
* 3 – Purpose of some circuits is very unclear. Description of most signal conditioning circuitry limited to discussion only topology with no reference to signal conditioning or gain. Power supplies ignored. Mechanical mounting is very weak.
* 2 – Most circuits are very unclear. Signal conditioning circuits mentioned only trivially. Mechanical mounting not described.
* 1 – Design details fundamentally wrong or missing.

### Modeling 
An explanation of how MATLAB, historical data, or your own models were used to predict the robot’s performance, the sensor measurements versus time, and how the modeling results informed the experimental protocol. There should be a similar analysis for each sensor.

* 5 – As above. Simulations or analytical models pursued, relevant data extracted for each sensor and control algorithm and modifications described and linked to simulation.
* 4 – Simulation or models present, relevant data extracted for multiple sensors / control algorithms.
* 3 – Simulation or models present, any relevant data extracted.
* 2 – Simulation or models present but very little relevant data is extracted.
* 1 – Simulations or models fundamentally wrong or missing.

### Experimental Procedure 
An explanation of the experimental protocol. e.g., The goals for each deployment, prepping the robot, starting the teensy code, deployment details, recovery details, retrieval of the data, and processing of the data.

* 5 – Reasonable description of launch procedure. Some team specific details.
* 3 – Poor description of launch procedure. Or generic / low effort regurgitation of
checklist
* 1 – Missing or very bad.

### Includes Required Sections

* 1 - Includes discussion of employment safety
* 0 - Does not include discussion of deployment safety

### Comparison of Data to Model 
A comparison of the modeled (or expected) data from 3.D with the retrieved data from 3.E. Graphical comparison is preferred, but written comparison should be used as appropriate, especially to explain the graphical data. Error bars or estimates should be included in all experimental quantities. Whether each deployment is compared individually or all deployments compared together will depend on the data sets and the results. Descriptions of the degree of agreement should be made and possible explanations of the discrepancies should be present.

* 5 – Well thought out graphical comparisons between simulated, analytical and
experimental results. Appropriate explanations in text. Error bars used carefully.
Analyze agreement with hypotheses.
* 4 – Reasonable data organization and graphics. Some evidence of margining deployment and model data into easily digestible formats. Some reasonable conclusions drawn about the comparison between deployment and model.
* 3 – Poor data organization (eg: copied and pasted MATLAB plots split over several figures) but a present and meaningful comparison of modeled data vs. deployment data.
* 2 – Poor data organization and poor analysis of results. Not well compared between model and flight, but some evidence of an attempt at comparison.
* 1 – Missing or very bad.

## Conclusion 
The conclusions should not be just a summary, but should be a summation of lessons learned, both about the process and of the comparison of the data and models. It should answer the question, “What does it all mean?” It should include recommendations for future work and/or future versions of the class.

* 5 – Summarizes, Lessons Learned, Clearly state conclusions from data, future work.
* 4 – Summarizes, Clearly states conclusions from data. Some other reflections.
* 3 – Summarizes, Some effort at stating conclusions from data,
* 2 – Summary only
* 1 – Missing or bad

## Acknowledgement 
List all non E80 personnel who helped. Be sure to briefly describe their contribution.

* 5 – Present, concise, complete
* 3 – Present with major oversights
* 1 – Missing

## References 
List and cite all relevant references.  Be especially careful to cite sources for figures that you have not drawn yourself.

* 5 – Present, follows proper format for Scientific Citations
* 3 – Present with major oversights
* 1 – Missing

## English usage 

### Grammar/Usage/Mechanics 
- Superior – Free of spelling, capitalization, and usage errors. Few, if any, errors in punctuation. Sophisticated and consistent command of standard English.
- Good – Number and type of errors does not interfere with meaning. Few, if any, spelling, capitalization, or usage errors.
- Marginal – Number and type of errors may interfere with meaning at some points. Some spelling, capitalization, or usage errors. Some fragments and/or run-ons. Some errors in punctuation.
- Inadequate – Number and type of errors obscure meaning. Frequent errors in spelling, capitalization, and usage. Many fragments and/or run-ons. Serious and frequent punctuation errors.

### Style/Organization 

#### Transitions
- Superior – Ideas/paragraphs/sections are connected by effective transition words and phrases.Precise, interesting, and accurate word choice. Writing style enhances readability of writing.
- Good – Transitions used. Word choice is adequate to convey meaning.
- Marginal – Few or no transitions. Overall style choppy.
- Inadequate – No transitions. Sentence style choppy. Vocabulary limited.

#### Focus
- Superior – Language choices (degree of jargon) and use of background material reflect attention to audience. Writing has a clear, distinct focus.
- Good – Most material is appropriate to audience. Focus may be unclear at points.
- Marginal – Little evidence of attentiveness to audience. Focus on topic not consistently sustained.
- Inadequate – No evidence of attentiveness to audience. Writing is unfocused.

#### Organization
- Superior – Generally well-developed ideas have a logical flow. Introductory and closing material is used effectively. Piece has a sense of completeness.
- Good – Ideas may not be in their most effective order. Some main points are underdeveloped. Some attempt is made at introductory and closing material; piece has a sense of completeness.
- Marginal – Order of ideas not entirely effective. Lack of distinction between main and supporting statements. Piece seems incomplete.
- Inadequate – Lack of cohesive plan for presentation of material. No opening or closing. Incomplete.

#### Elaboration / Support

- Superior – Each main idea is supported by detailed data or reasoning. All details are related to topic. Complete, correct documentation of a wide variety of sources.
- Good – Details and/or data in some paragraphs may be sketchy; details may be insufficient to reach conclusions. All details are related to topic. Complete documentation of a variety of sources.
- Marginal – Details may appear to be listed rather than integrated into coherent flow; some details are irrelevant. Marginal documentation of sources; some key sources may be missing.
- Inadequate – Half or more of conclusions/main ideas are not supported by details. Half or more details cited are irrelevant. Inadequate documentation of inadequate sources.
