---
title: E80 Lab Inventory
---

## Electrical

### Resistors

The table below is in units of Ohms.  Entries indicate we have resistors, blank spaces indicate that resistors are not stocked.  Standard SI prefixes (k for kilo, M for mega) are used.

| 1-10 | 10 -100 | 100-1k | 1k-10k | 10k - 100k | 100k - 1M | 1M - 10M | 10M-100M | 
|------|---------|--------|--------|------------|-----------|----------|----------|
| 1    | 10      | 100    | 1k     | 10k        | 100k      | 1M       | 10M      |
|      | 20      | 200    | 2k     |            | 200k      |          | 20M      |
|      |         | 220    |        |            |           |          |          |
|      |         |        |        | 47k        | 470k      |          |          | 
|      |         | 510    | 5.1k   |            |           |          |          | 
|      |         |        |        |            |           | 9.1M     |          |

These resistors are the ones stocked in the E80 parts boxes (according to the [E12 preferred numbers](https://en.wikipedia.org/wiki/E_series_of_preferred_numbers)). Many other resistors are available in the analog lab closet.  Don't take resistors (or any other components) from E84 stock.

### Capacitors

The table below is in units of Farads.  Entries indicate we have capacitors, blank spaces indicate that resistors are not stocked.  Standard SI prefixes (n for nano, $\mu$ for micro) are used.

| 1n-10n | 10n -100n | 100n-1$\mu$ | 1$\mu$-10$\mu$ | 10$\mu$ - 100$\mu$ | 100$\mu$ - 1m |
|--------|-----------|-------------|----------------|--------------------|---------------|
| 1n     |           | 100n        | 1$\mu$         | 10$\mu$            |               |
|        |           | 330n        |                |                    |               |
|        |           | 470n        |                |                    | 470$\mu$      |

These capacitors are the ones stocked in the E80 parts boxes. Many other capacitors are available in the analog lab closet.  Don't take capacitors (or any other components) from E84 stock.

### Other Passives

* Potentiometers (in the drawers labeled "trimmer". Values include 1k and 10k.)
* 10k thermistor (490-12820-ND)
* 47k thermistor (490-14853-ND)
* 100k thermistor (490-5633-ND)
* Infrared LED (1080-1071-ND)
* Photodiode (365-1085-ND)
* Red LED (L513SRD-C)

### Op amps

* OP07
* MCP601
* MCP6002
* MCP6004
* AD623 (an instrumentation amp, not an op amp)
* TL081

### Sensors and Other Chips

* Solid state temperature sensor (MCP9701A-E/TO-ND)
* Absolute pressure sensor (MPX5700ASX-ND) tracked with checkout sheet and error reports
* Microphone (Mfg. part number: CME-1538-100LB; Digi-Key #: 102-2190-ND)
* Thermocouple wire
* 555 Timer (296-21753-5-ND)
* 5V regulator (MC7805CT-BPMS-ND)
* LM384 audio amp
* Teensy 4.0 tracked with checkout sheet and error reports
* Adafruit Ultimate GPS tracked with checkout sheet and error reports
* GPS antennas

### Connectors

* 16 DIP chip socket
* 8 DIP chip socket
* Male headers
* Female headers
* 26 Pos male ribbon cable connector (ED10537-ND)
* 26 Pos female ribbon cable connector (ED10504-ND)

## Mechanical

* Waterproof boxes tracked with checkout sheet and error reports
* PVC (same as E79)
* Velcro
* Plastic mesh
* Hex standoff (93505A518)
* Hex nut (91841A003)
* screw 1/4" (91792A077)
* screw 3/8" (91792A079)
* Rubber foam sheet (B074HQ9TBP)
* Zip ties
* Penetrator Assembly
* Nylon bolt (95868A631)
* Nylon nut (94812A930)
* Rubber washer (90130A033)
* marine putty (50172)
* Marine epoxy (202057892)
* Motor Assembly
* 12 DC Motor (232022)
* Film Canister (B00OZQTQB4)
* Propellor (LXE472)
* threaded motor coupler (LXK089)
* T-Nut (90975A002)
* Lock Nut (91831A005)
* Wax (2793K31)
* Electrical Tape (B01ETZ6SOI)
* Pressure sensor tubing (B00E6BCV0G)

## Other

* Micro sd card and adapter tracked with checkout sheet and error reports
* Battery tracked with checkout sheet and error reports
* Go Pro cameras - limited supply.  Must provide a very good design.
* pH sensor - limited supply. Must provide a very good design.
* USB cameras - limited supply. First come first served. (your phones are better)
* DAEX25W Speaker ~ 6x available for prototyping but not for permanent installation.  Buy your own for your robot.


